### ISSUE TITLE
Project unable to load

### ISSUE THREAD

**Issue by AndyBraham** [thangchung/blog-core#19]
I just downloaded this project and opened it in Visual Studio 2017 (15.9.4) and I am recieving errors on all the "Host" projects. Seems like something in the .csproj files is missing, I recieve the error "Project file is incomplete. Expected imports are missing. 

When I tried to restore the Nuget packages I did notice one error "Package Microsoft.EntityFrameworkCore.Tools.DotNet 2.0.0 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Microsoft.EntityFrameworkCore.Tools.DotNet 2.0.0 supports: netcoreapp2.0 (.NETCoreApp,Version=v2.0)	BlogCore.Migrator"

**Comment by Herve-M** [comment]
It's because of the `global.json`[docs](https://docs.microsoft.com/en-us/dotnet/core/tools/global-json) who force `2.0.0`, and you may have installed the Net Core SDK 2.2.X who only bring 1.1.0 + 2.1.* < versions. 

Just remove the file or target the last version you have locally (`dotnet  --list-sdks` or `dotnet new globaljson --force` ) ;-)

**Comment by thangchung** [comment]
@AndyBraham I gonna upgrade this project into .NET 3.0 soon after Microsoft release it in the public version. Just waiting for it
@Herve-M Thanks for your great insight in this project 👍

**Comment by thangchung** [comment]
See the new upgrade version at https://github.com/thangchung/blog-core/tree/blazor branch for .NET 3.0 Preview 5
